version: '3.0'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  # nearme-cms-server:
  #   build:
  #     context: .
  #     dockerfile: nearme-cms-server-Dockerfile
  #   volumes:
  #     - .:/usr/app/
  #   environment:
  #     APP_ENV: .env.dev
  #   command: [sh, -c, 'APP_ENV=.env.dev npm start']
  #   ports:
  #     - '3001:3001'
  #   links:
  #     - mongo
  #   depends_on:
  #     - mongo
 