version: '2.0'

services:
  mongo:
    image: mongo
    # ports:
    #   - "27019:27017"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    environment:
      NODE_ENV: docker
    command: [sh, -c, 'npm run start-cms-do-docker']
    ports:
      - '1339:1339'
    links:
      - mongo
    depends_on:
      - mongo
 